version: 0.2

phases:
  pre_build:
    commands:
      - echo install packages...
      - npm install --unsafe-perm
  build:
    commands:
      - echo Create build...
      - npm run build
  post_build:
    commands:
      - echo Removing node modules folder...
      - rm -rf node_modules/
artifacts:
  files:
    - "**/*"
  base-directory: "."
